name: Two Jobs Workflow

on:
  push:
    branches:
      - main  # This triggers the automatic job on push to main
  workflow_dispatch:  # This allows manual triggering for the manual job

jobs:
  automatic_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Automatic Job
        run: |
          echo "Running automatic job!"
          echo "This is the result from the automatic job" > result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: automatic-job-results
          path: result.txt  # Make sure this file is created before uploading

  manual_job:
    runs-on: ubuntu-latest
    if: github.event.inputs.manual_job == 'true'  # Only run if manually triggered
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: automatic-job-results
        
      - name: Use Artifact
        run: |
          echo "Processing artifact from automatic job"
          cat result.txt  # Use the result from the automatic job
