name: Conditional Workflow with Separate Jobs

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      task:
        description: "Choose a task to run"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - test

jobs:
  build-job:
    if: ${{ github.event.inputs.task == 'build' }}  # Run only if 'build' is selected
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Run Build Task
        run: |
          echo "Running build task..."
          # Add your build commands here, e.g., npm run build

  test-job:
    if: ${{ github.event.inputs.task == 'test' }}  # Run only if 'test' is selected
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Run Test Task
        run: |
          echo "Running test task..."
          # Add your test commands here, e.g., npm test
