name: Multi-Stage CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      deploy:  # Define the input to trigger deploy manually
        description: 'Deploy the application'
        required: false
        default: 'false'
        type: string

jobs:
  package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Package Build
        run: echo "Running package build"

      - name: Upload Build Package
        uses: actions/upload-artifact@v3
        with:
          name: build-package
          path: ./build-package.zip  # Replace with actual path to the build artifact

  build_docker:
    runs-on: ubuntu-latest
    needs: package_build  # Runs only after the package_build job is completed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Package
        uses: actions/download-artifact@v3
        with:
          name: build-package

      - name: Build Docker Image
        run: echo "Building Docker image"

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker  # Wait for build_docker to complete
    if: github.event.inputs.deploy == 'true'  # Only run if manually triggered with deploy=true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: echo "Deploying application"
