name: Generate DAG

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Notebook file name'
        required: true
      template:
        description: 'DAG template'
        required: true
        default: 'default.py'
        type: choice
        options:
          - default.py
          - template2.py

jobs:
  generate-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jinja2
      run: pip install jinja2

    - name: Generate file from template
      run: |
        python .github/generate_dag.py ${{ github.event.inputs.template }} ${{ github.event.inputs.filename }}

    - name: Checkout target repository
      run: |
        git clone https://github.com/sergeygazaryan/dag.git
        cd dag
        mkdir -p generated_files
        cp ../generated_files/${{ github.event.inputs.filename }}.py generated_files/

    - name: Commit and push changes to target repository
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.DAG_REPO_TOKEN }}
      run: |
        cd dag
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add generated_files/
        git commit -m "Add generated file ${{ github.event.inputs.filename }}"
        git push https://$PERSONAL_ACCESS_TOKEN@github.com/sergeygazaryan/dag.git
