name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Choose a task"
        required: true
        default: "build"
        type: string

jobs:
  build-job:
    if: ${{ github.event.inputs.task == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build project
        run: echo "Building the project..."

  test-job:
    if: ${{ github.event.inputs.task == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running tests..."
