name: Multi-Stage Pipeline

on:
  workflow_dispatch:  # Allows you to manually trigger the entire workflow

jobs:
  package_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Package Build
        run: echo "Running package build..."

  build_docker:
    runs-on: ubuntu-latest
    needs: package_build  # Runs only after the package_build job is completed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: echo "Building Docker image..."

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker  # Wait for build_docker to complete
    if: ${{ github.event.inputs.deploy == 'true' }}  # Deploy only if manually triggered
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: echo "Deploying application..."
