name: Conditional Workflow with Matrix

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      task:
        description: "Choose a task to run"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - test

jobs:
  dynamic-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [build, test]  # Define possible tasks in the matrix

    # This condition ensures that only the job matching the input is created and run
    if: ${{ matrix.task == github.event.inputs.task }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Build Task
        if: ${{ matrix.task == 'build' }}
        run: |
          echo "Running build task..."
          # Add your build commands here, e.g., npm run build

      - name: Run Test Task
        if: ${{ matrix.task == 'test' }}
        run: |
          echo "Running test task..."
          # Add your test commands here, e.g., npm test
