name: Conditional Workflow with Matrix

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Choose a task"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - test

jobs:
  dynamic-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [build, test]  # Define tasks in the matrix

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run task
        run: echo "Running task: ${{ matrix.task }}"

    # Conditionally run the matrix job based on input
    if: ${{ matrix.task == github.event.inputs.task }}
